// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: indicators.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TechnicalIndicators_CalculateRSI_FullMethodName            = "/indicators.TechnicalIndicators/CalculateRSI"
	TechnicalIndicators_CalculateMACD_FullMethodName           = "/indicators.TechnicalIndicators/CalculateMACD"
	TechnicalIndicators_CalculateBollingerBands_FullMethodName = "/indicators.TechnicalIndicators/CalculateBollingerBands"
	TechnicalIndicators_CalculateEMA_FullMethodName            = "/indicators.TechnicalIndicators/CalculateEMA"
	TechnicalIndicators_DetectVolumeSpike_FullMethodName       = "/indicators.TechnicalIndicators/DetectVolumeSpike"
	TechnicalIndicators_AnalyzeAll_FullMethodName              = "/indicators.TechnicalIndicators/AnalyzeAll"
)

// TechnicalIndicatorsClient is the client API for TechnicalIndicators service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// grpc service
type TechnicalIndicatorsClient interface {
	CalculateRSI(ctx context.Context, in *RSIRequest, opts ...grpc.CallOption) (*RSIResponse, error)
	CalculateMACD(ctx context.Context, in *MACDRequest, opts ...grpc.CallOption) (*MACDResponse, error)
	CalculateBollingerBands(ctx context.Context, in *BollingerRequest, opts ...grpc.CallOption) (*BollingerResponse, error)
	CalculateEMA(ctx context.Context, in *EMARequest, opts ...grpc.CallOption) (*EMAResponse, error)
	DetectVolumeSpike(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*VolumeResponse, error)
	AnalyzeAll(ctx context.Context, in *AnalyzeAllRequest, opts ...grpc.CallOption) (*AnalyzeAllResponse, error)
}

type technicalIndicatorsClient struct {
	cc grpc.ClientConnInterface
}

func NewTechnicalIndicatorsClient(cc grpc.ClientConnInterface) TechnicalIndicatorsClient {
	return &technicalIndicatorsClient{cc}
}

func (c *technicalIndicatorsClient) CalculateRSI(ctx context.Context, in *RSIRequest, opts ...grpc.CallOption) (*RSIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RSIResponse)
	err := c.cc.Invoke(ctx, TechnicalIndicators_CalculateRSI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *technicalIndicatorsClient) CalculateMACD(ctx context.Context, in *MACDRequest, opts ...grpc.CallOption) (*MACDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MACDResponse)
	err := c.cc.Invoke(ctx, TechnicalIndicators_CalculateMACD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *technicalIndicatorsClient) CalculateBollingerBands(ctx context.Context, in *BollingerRequest, opts ...grpc.CallOption) (*BollingerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BollingerResponse)
	err := c.cc.Invoke(ctx, TechnicalIndicators_CalculateBollingerBands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *technicalIndicatorsClient) CalculateEMA(ctx context.Context, in *EMARequest, opts ...grpc.CallOption) (*EMAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EMAResponse)
	err := c.cc.Invoke(ctx, TechnicalIndicators_CalculateEMA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *technicalIndicatorsClient) DetectVolumeSpike(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*VolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VolumeResponse)
	err := c.cc.Invoke(ctx, TechnicalIndicators_DetectVolumeSpike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *technicalIndicatorsClient) AnalyzeAll(ctx context.Context, in *AnalyzeAllRequest, opts ...grpc.CallOption) (*AnalyzeAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeAllResponse)
	err := c.cc.Invoke(ctx, TechnicalIndicators_AnalyzeAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TechnicalIndicatorsServer is the server API for TechnicalIndicators service.
// All implementations must embed UnimplementedTechnicalIndicatorsServer
// for forward compatibility.
//
// grpc service
type TechnicalIndicatorsServer interface {
	CalculateRSI(context.Context, *RSIRequest) (*RSIResponse, error)
	CalculateMACD(context.Context, *MACDRequest) (*MACDResponse, error)
	CalculateBollingerBands(context.Context, *BollingerRequest) (*BollingerResponse, error)
	CalculateEMA(context.Context, *EMARequest) (*EMAResponse, error)
	DetectVolumeSpike(context.Context, *VolumeRequest) (*VolumeResponse, error)
	AnalyzeAll(context.Context, *AnalyzeAllRequest) (*AnalyzeAllResponse, error)
	mustEmbedUnimplementedTechnicalIndicatorsServer()
}

// UnimplementedTechnicalIndicatorsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTechnicalIndicatorsServer struct{}

func (UnimplementedTechnicalIndicatorsServer) CalculateRSI(context.Context, *RSIRequest) (*RSIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateRSI not implemented")
}
func (UnimplementedTechnicalIndicatorsServer) CalculateMACD(context.Context, *MACDRequest) (*MACDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateMACD not implemented")
}
func (UnimplementedTechnicalIndicatorsServer) CalculateBollingerBands(context.Context, *BollingerRequest) (*BollingerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateBollingerBands not implemented")
}
func (UnimplementedTechnicalIndicatorsServer) CalculateEMA(context.Context, *EMARequest) (*EMAResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateEMA not implemented")
}
func (UnimplementedTechnicalIndicatorsServer) DetectVolumeSpike(context.Context, *VolumeRequest) (*VolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectVolumeSpike not implemented")
}
func (UnimplementedTechnicalIndicatorsServer) AnalyzeAll(context.Context, *AnalyzeAllRequest) (*AnalyzeAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeAll not implemented")
}
func (UnimplementedTechnicalIndicatorsServer) mustEmbedUnimplementedTechnicalIndicatorsServer() {}
func (UnimplementedTechnicalIndicatorsServer) testEmbeddedByValue()                             {}

// UnsafeTechnicalIndicatorsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TechnicalIndicatorsServer will
// result in compilation errors.
type UnsafeTechnicalIndicatorsServer interface {
	mustEmbedUnimplementedTechnicalIndicatorsServer()
}

func RegisterTechnicalIndicatorsServer(s grpc.ServiceRegistrar, srv TechnicalIndicatorsServer) {
	// If the following call panics, it indicates UnimplementedTechnicalIndicatorsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TechnicalIndicators_ServiceDesc, srv)
}

func _TechnicalIndicators_CalculateRSI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RSIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechnicalIndicatorsServer).CalculateRSI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TechnicalIndicators_CalculateRSI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechnicalIndicatorsServer).CalculateRSI(ctx, req.(*RSIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TechnicalIndicators_CalculateMACD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MACDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechnicalIndicatorsServer).CalculateMACD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TechnicalIndicators_CalculateMACD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechnicalIndicatorsServer).CalculateMACD(ctx, req.(*MACDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TechnicalIndicators_CalculateBollingerBands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BollingerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechnicalIndicatorsServer).CalculateBollingerBands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TechnicalIndicators_CalculateBollingerBands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechnicalIndicatorsServer).CalculateBollingerBands(ctx, req.(*BollingerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TechnicalIndicators_CalculateEMA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EMARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechnicalIndicatorsServer).CalculateEMA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TechnicalIndicators_CalculateEMA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechnicalIndicatorsServer).CalculateEMA(ctx, req.(*EMARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TechnicalIndicators_DetectVolumeSpike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechnicalIndicatorsServer).DetectVolumeSpike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TechnicalIndicators_DetectVolumeSpike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechnicalIndicatorsServer).DetectVolumeSpike(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TechnicalIndicators_AnalyzeAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechnicalIndicatorsServer).AnalyzeAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TechnicalIndicators_AnalyzeAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechnicalIndicatorsServer).AnalyzeAll(ctx, req.(*AnalyzeAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TechnicalIndicators_ServiceDesc is the grpc.ServiceDesc for TechnicalIndicators service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TechnicalIndicators_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "indicators.TechnicalIndicators",
	HandlerType: (*TechnicalIndicatorsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateRSI",
			Handler:    _TechnicalIndicators_CalculateRSI_Handler,
		},
		{
			MethodName: "CalculateMACD",
			Handler:    _TechnicalIndicators_CalculateMACD_Handler,
		},
		{
			MethodName: "CalculateBollingerBands",
			Handler:    _TechnicalIndicators_CalculateBollingerBands_Handler,
		},
		{
			MethodName: "CalculateEMA",
			Handler:    _TechnicalIndicators_CalculateEMA_Handler,
		},
		{
			MethodName: "DetectVolumeSpike",
			Handler:    _TechnicalIndicators_DetectVolumeSpike_Handler,
		},
		{
			MethodName: "AnalyzeAll",
			Handler:    _TechnicalIndicators_AnalyzeAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "indicators.proto",
}
