// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: indicators.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// candle data for indicator calculations
type Candle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Open          float64                `protobuf:"fixed64,1,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,2,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,3,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,4,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candle) Reset() {
	*x = Candle{}
	mi := &file_indicators_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candle) ProtoMessage() {}

func (x *Candle) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candle.ProtoReflect.Descriptor instead.
func (*Candle) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{0}
}

func (x *Candle) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Candle) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Candle) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Candle) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Candle) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Candle) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RSIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candles       []*Candle              `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	Period        int32                  `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"` // default 14
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RSIRequest) Reset() {
	*x = RSIRequest{}
	mi := &file_indicators_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RSIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSIRequest) ProtoMessage() {}

func (x *RSIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSIRequest.ProtoReflect.Descriptor instead.
func (*RSIRequest) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{1}
}

func (x *RSIRequest) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *RSIRequest) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

type RSIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Signal        string                 `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`          // OVERSOLD, NEUTRAL, OVERBOUGHT
	Series        []float64              `protobuf:"fixed64,3,rep,packed,name=series,proto3" json:"series,omitempty"` // full rsi series
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RSIResponse) Reset() {
	*x = RSIResponse{}
	mi := &file_indicators_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RSIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSIResponse) ProtoMessage() {}

func (x *RSIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSIResponse.ProtoReflect.Descriptor instead.
func (*RSIResponse) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{2}
}

func (x *RSIResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *RSIResponse) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *RSIResponse) GetSeries() []float64 {
	if x != nil {
		return x.Series
	}
	return nil
}

type MACDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candles       []*Candle              `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	FastPeriod    int32                  `protobuf:"varint,2,opt,name=fast_period,json=fastPeriod,proto3" json:"fast_period,omitempty"`       // default 12
	SlowPeriod    int32                  `protobuf:"varint,3,opt,name=slow_period,json=slowPeriod,proto3" json:"slow_period,omitempty"`       // default 26
	SignalPeriod  int32                  `protobuf:"varint,4,opt,name=signal_period,json=signalPeriod,proto3" json:"signal_period,omitempty"` // default 9
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MACDRequest) Reset() {
	*x = MACDRequest{}
	mi := &file_indicators_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MACDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MACDRequest) ProtoMessage() {}

func (x *MACDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MACDRequest.ProtoReflect.Descriptor instead.
func (*MACDRequest) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{3}
}

func (x *MACDRequest) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *MACDRequest) GetFastPeriod() int32 {
	if x != nil {
		return x.FastPeriod
	}
	return 0
}

func (x *MACDRequest) GetSlowPeriod() int32 {
	if x != nil {
		return x.SlowPeriod
	}
	return 0
}

func (x *MACDRequest) GetSignalPeriod() int32 {
	if x != nil {
		return x.SignalPeriod
	}
	return 0
}

type MACDResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MacdLine        float64                `protobuf:"fixed64,1,opt,name=macd_line,json=macdLine,proto3" json:"macd_line,omitempty"`
	SignalLine      float64                `protobuf:"fixed64,2,opt,name=signal_line,json=signalLine,proto3" json:"signal_line,omitempty"`
	Histogram       float64                `protobuf:"fixed64,3,opt,name=histogram,proto3" json:"histogram,omitempty"`
	Signal          string                 `protobuf:"bytes,4,opt,name=signal,proto3" json:"signal,omitempty"` // BULLISH, BEARISH, NEUTRAL
	Crossover       bool                   `protobuf:"varint,5,opt,name=crossover,proto3" json:"crossover,omitempty"`
	MacdSeries      []float64              `protobuf:"fixed64,6,rep,packed,name=macd_series,json=macdSeries,proto3" json:"macd_series,omitempty"`
	SignalSeries    []float64              `protobuf:"fixed64,7,rep,packed,name=signal_series,json=signalSeries,proto3" json:"signal_series,omitempty"`
	HistogramSeries []float64              `protobuf:"fixed64,8,rep,packed,name=histogram_series,json=histogramSeries,proto3" json:"histogram_series,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MACDResponse) Reset() {
	*x = MACDResponse{}
	mi := &file_indicators_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MACDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MACDResponse) ProtoMessage() {}

func (x *MACDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MACDResponse.ProtoReflect.Descriptor instead.
func (*MACDResponse) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{4}
}

func (x *MACDResponse) GetMacdLine() float64 {
	if x != nil {
		return x.MacdLine
	}
	return 0
}

func (x *MACDResponse) GetSignalLine() float64 {
	if x != nil {
		return x.SignalLine
	}
	return 0
}

func (x *MACDResponse) GetHistogram() float64 {
	if x != nil {
		return x.Histogram
	}
	return 0
}

func (x *MACDResponse) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *MACDResponse) GetCrossover() bool {
	if x != nil {
		return x.Crossover
	}
	return false
}

func (x *MACDResponse) GetMacdSeries() []float64 {
	if x != nil {
		return x.MacdSeries
	}
	return nil
}

func (x *MACDResponse) GetSignalSeries() []float64 {
	if x != nil {
		return x.SignalSeries
	}
	return nil
}

func (x *MACDResponse) GetHistogramSeries() []float64 {
	if x != nil {
		return x.HistogramSeries
	}
	return nil
}

type BollingerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candles       []*Candle              `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	Period        int32                  `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"`                // default 20
	StdDev        float64                `protobuf:"fixed64,3,opt,name=std_dev,json=stdDev,proto3" json:"std_dev,omitempty"` // default 2.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BollingerRequest) Reset() {
	*x = BollingerRequest{}
	mi := &file_indicators_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BollingerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BollingerRequest) ProtoMessage() {}

func (x *BollingerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BollingerRequest.ProtoReflect.Descriptor instead.
func (*BollingerRequest) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{5}
}

func (x *BollingerRequest) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *BollingerRequest) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *BollingerRequest) GetStdDev() float64 {
	if x != nil {
		return x.StdDev
	}
	return 0
}

type BollingerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upper         float64                `protobuf:"fixed64,1,opt,name=upper,proto3" json:"upper,omitempty"`
	Middle        float64                `protobuf:"fixed64,2,opt,name=middle,proto3" json:"middle,omitempty"`
	Lower         float64                `protobuf:"fixed64,3,opt,name=lower,proto3" json:"lower,omitempty"`
	Bandwidth     float64                `protobuf:"fixed64,4,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	PercentB      float64                `protobuf:"fixed64,5,opt,name=percent_b,json=percentB,proto3" json:"percent_b,omitempty"` // where price sits relative to bands (0-1)
	Signal        string                 `protobuf:"bytes,6,opt,name=signal,proto3" json:"signal,omitempty"`                       // UPPER_BAND, MIDDLE, LOWER_BAND, SQUEEZE
	UpperSeries   []float64              `protobuf:"fixed64,7,rep,packed,name=upper_series,json=upperSeries,proto3" json:"upper_series,omitempty"`
	MiddleSeries  []float64              `protobuf:"fixed64,8,rep,packed,name=middle_series,json=middleSeries,proto3" json:"middle_series,omitempty"`
	LowerSeries   []float64              `protobuf:"fixed64,9,rep,packed,name=lower_series,json=lowerSeries,proto3" json:"lower_series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BollingerResponse) Reset() {
	*x = BollingerResponse{}
	mi := &file_indicators_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BollingerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BollingerResponse) ProtoMessage() {}

func (x *BollingerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BollingerResponse.ProtoReflect.Descriptor instead.
func (*BollingerResponse) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{6}
}

func (x *BollingerResponse) GetUpper() float64 {
	if x != nil {
		return x.Upper
	}
	return 0
}

func (x *BollingerResponse) GetMiddle() float64 {
	if x != nil {
		return x.Middle
	}
	return 0
}

func (x *BollingerResponse) GetLower() float64 {
	if x != nil {
		return x.Lower
	}
	return 0
}

func (x *BollingerResponse) GetBandwidth() float64 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *BollingerResponse) GetPercentB() float64 {
	if x != nil {
		return x.PercentB
	}
	return 0
}

func (x *BollingerResponse) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *BollingerResponse) GetUpperSeries() []float64 {
	if x != nil {
		return x.UpperSeries
	}
	return nil
}

func (x *BollingerResponse) GetMiddleSeries() []float64 {
	if x != nil {
		return x.MiddleSeries
	}
	return nil
}

func (x *BollingerResponse) GetLowerSeries() []float64 {
	if x != nil {
		return x.LowerSeries
	}
	return nil
}

type EMARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candles       []*Candle              `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	Period        int32                  `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"` // e.g. 9, 21, 50, 200
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EMARequest) Reset() {
	*x = EMARequest{}
	mi := &file_indicators_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EMARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EMARequest) ProtoMessage() {}

func (x *EMARequest) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EMARequest.ProtoReflect.Descriptor instead.
func (*EMARequest) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{7}
}

func (x *EMARequest) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *EMARequest) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

type EMAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Trend         string                 `protobuf:"bytes,2,opt,name=trend,proto3" json:"trend,omitempty"` // ABOVE (price > ema), BELOW (price < ema)
	Series        []float64              `protobuf:"fixed64,3,rep,packed,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EMAResponse) Reset() {
	*x = EMAResponse{}
	mi := &file_indicators_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EMAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EMAResponse) ProtoMessage() {}

func (x *EMAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EMAResponse.ProtoReflect.Descriptor instead.
func (*EMAResponse) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{8}
}

func (x *EMAResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *EMAResponse) GetTrend() string {
	if x != nil {
		return x.Trend
	}
	return ""
}

func (x *EMAResponse) GetSeries() []float64 {
	if x != nil {
		return x.Series
	}
	return nil
}

type VolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candles       []*Candle              `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	Lookback      int32                  `protobuf:"varint,2,opt,name=lookback,proto3" json:"lookback,omitempty"`    // default 20
	Threshold     float64                `protobuf:"fixed64,3,opt,name=threshold,proto3" json:"threshold,omitempty"` // default 2.0 (2x average volume)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeRequest) Reset() {
	*x = VolumeRequest{}
	mi := &file_indicators_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeRequest) ProtoMessage() {}

func (x *VolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeRequest.ProtoReflect.Descriptor instead.
func (*VolumeRequest) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{9}
}

func (x *VolumeRequest) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *VolumeRequest) GetLookback() int32 {
	if x != nil {
		return x.Lookback
	}
	return 0
}

func (x *VolumeRequest) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type VolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSpike       bool                   `protobuf:"varint,1,opt,name=is_spike,json=isSpike,proto3" json:"is_spike,omitempty"`
	CurrentVolume float64                `protobuf:"fixed64,2,opt,name=current_volume,json=currentVolume,proto3" json:"current_volume,omitempty"`
	AverageVolume float64                `protobuf:"fixed64,3,opt,name=average_volume,json=averageVolume,proto3" json:"average_volume,omitempty"`
	Ratio         float64                `protobuf:"fixed64,4,opt,name=ratio,proto3" json:"ratio,omitempty"`
	Signal        string                 `protobuf:"bytes,5,opt,name=signal,proto3" json:"signal,omitempty"` // SPIKE, NORMAL, LOW
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeResponse) Reset() {
	*x = VolumeResponse{}
	mi := &file_indicators_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeResponse) ProtoMessage() {}

func (x *VolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeResponse.ProtoReflect.Descriptor instead.
func (*VolumeResponse) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{10}
}

func (x *VolumeResponse) GetIsSpike() bool {
	if x != nil {
		return x.IsSpike
	}
	return false
}

func (x *VolumeResponse) GetCurrentVolume() float64 {
	if x != nil {
		return x.CurrentVolume
	}
	return 0
}

func (x *VolumeResponse) GetAverageVolume() float64 {
	if x != nil {
		return x.AverageVolume
	}
	return 0
}

func (x *VolumeResponse) GetRatio() float64 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *VolumeResponse) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

type ATRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candles       []*Candle              `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	Period        int32                  `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"` // default 14
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ATRRequest) Reset() {
	*x = ATRRequest{}
	mi := &file_indicators_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ATRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ATRRequest) ProtoMessage() {}

func (x *ATRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ATRRequest.ProtoReflect.Descriptor instead.
func (*ATRRequest) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{11}
}

func (x *ATRRequest) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *ATRRequest) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

type ATRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Percent       float64                `protobuf:"fixed64,2,opt,name=percent,proto3" json:"percent,omitempty"` // atr as % of close
	Signal        string                 `protobuf:"bytes,3,opt,name=signal,proto3" json:"signal,omitempty"`     // HIGH, NORMAL, LOW
	Series        []float64              `protobuf:"fixed64,4,rep,packed,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ATRResponse) Reset() {
	*x = ATRResponse{}
	mi := &file_indicators_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ATRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ATRResponse) ProtoMessage() {}

func (x *ATRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ATRResponse.ProtoReflect.Descriptor instead.
func (*ATRResponse) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{12}
}

func (x *ATRResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ATRResponse) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *ATRResponse) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *ATRResponse) GetSeries() []float64 {
	if x != nil {
		return x.Series
	}
	return nil
}

type ADXRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candles       []*Candle              `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	Period        int32                  `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"` // default 14
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ADXRequest) Reset() {
	*x = ADXRequest{}
	mi := &file_indicators_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ADXRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADXRequest) ProtoMessage() {}

func (x *ADXRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADXRequest.ProtoReflect.Descriptor instead.
func (*ADXRequest) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{13}
}

func (x *ADXRequest) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *ADXRequest) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

type ADXResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`                     // adx 0-100
	PlusDi        float64                `protobuf:"fixed64,2,opt,name=plus_di,json=plusDi,proto3" json:"plus_di,omitempty"`     // +DI
	MinusDi       float64                `protobuf:"fixed64,3,opt,name=minus_di,json=minusDi,proto3" json:"minus_di,omitempty"`  // -DI
	Signal        string                 `protobuf:"bytes,4,opt,name=signal,proto3" json:"signal,omitempty"`                     // STRONG_TREND, TRENDING, WEAK, NO_TREND
	TrendDir      string                 `protobuf:"bytes,5,opt,name=trend_dir,json=trendDir,proto3" json:"trend_dir,omitempty"` // UP, DOWN, NEUTRAL
	Series        []float64              `protobuf:"fixed64,6,rep,packed,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ADXResponse) Reset() {
	*x = ADXResponse{}
	mi := &file_indicators_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ADXResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADXResponse) ProtoMessage() {}

func (x *ADXResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADXResponse.ProtoReflect.Descriptor instead.
func (*ADXResponse) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{14}
}

func (x *ADXResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ADXResponse) GetPlusDi() float64 {
	if x != nil {
		return x.PlusDi
	}
	return 0
}

func (x *ADXResponse) GetMinusDi() float64 {
	if x != nil {
		return x.MinusDi
	}
	return 0
}

func (x *ADXResponse) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *ADXResponse) GetTrendDir() string {
	if x != nil {
		return x.TrendDir
	}
	return ""
}

func (x *ADXResponse) GetSeries() []float64 {
	if x != nil {
		return x.Series
	}
	return nil
}

type StochasticRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candles       []*Candle              `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	KPeriod       int32                  `protobuf:"varint,2,opt,name=k_period,json=kPeriod,proto3" json:"k_period,omitempty"` // default 14
	DPeriod       int32                  `protobuf:"varint,3,opt,name=d_period,json=dPeriod,proto3" json:"d_period,omitempty"` // default 3
	Smooth        int32                  `protobuf:"varint,4,opt,name=smooth,proto3" json:"smooth,omitempty"`                  // default 3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StochasticRequest) Reset() {
	*x = StochasticRequest{}
	mi := &file_indicators_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StochasticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StochasticRequest) ProtoMessage() {}

func (x *StochasticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StochasticRequest.ProtoReflect.Descriptor instead.
func (*StochasticRequest) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{15}
}

func (x *StochasticRequest) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *StochasticRequest) GetKPeriod() int32 {
	if x != nil {
		return x.KPeriod
	}
	return 0
}

func (x *StochasticRequest) GetDPeriod() int32 {
	if x != nil {
		return x.DPeriod
	}
	return 0
}

func (x *StochasticRequest) GetSmooth() int32 {
	if x != nil {
		return x.Smooth
	}
	return 0
}

type StochasticResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	K             float64                `protobuf:"fixed64,1,opt,name=k,proto3" json:"k,omitempty"`         // %K 0-100
	D             float64                `protobuf:"fixed64,2,opt,name=d,proto3" json:"d,omitempty"`         // %D 0-100
	Signal        string                 `protobuf:"bytes,3,opt,name=signal,proto3" json:"signal,omitempty"` // OVERSOLD, NEUTRAL, OVERBOUGHT, BULLISH_CROSS, BEARISH_CROSS
	KSeries       []float64              `protobuf:"fixed64,4,rep,packed,name=k_series,json=kSeries,proto3" json:"k_series,omitempty"`
	DSeries       []float64              `protobuf:"fixed64,5,rep,packed,name=d_series,json=dSeries,proto3" json:"d_series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StochasticResponse) Reset() {
	*x = StochasticResponse{}
	mi := &file_indicators_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StochasticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StochasticResponse) ProtoMessage() {}

func (x *StochasticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StochasticResponse.ProtoReflect.Descriptor instead.
func (*StochasticResponse) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{16}
}

func (x *StochasticResponse) GetK() float64 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *StochasticResponse) GetD() float64 {
	if x != nil {
		return x.D
	}
	return 0
}

func (x *StochasticResponse) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *StochasticResponse) GetKSeries() []float64 {
	if x != nil {
		return x.KSeries
	}
	return nil
}

func (x *StochasticResponse) GetDSeries() []float64 {
	if x != nil {
		return x.DSeries
	}
	return nil
}

type RegimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candles       []*Candle              `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	Period        int32                  `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"` // default 14
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegimeRequest) Reset() {
	*x = RegimeRequest{}
	mi := &file_indicators_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegimeRequest) ProtoMessage() {}

func (x *RegimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegimeRequest.ProtoReflect.Descriptor instead.
func (*RegimeRequest) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{17}
}

func (x *RegimeRequest) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *RegimeRequest) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

type RegimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regime        string                 `protobuf:"bytes,1,opt,name=regime,proto3" json:"regime,omitempty"` // trending, ranging, volatile, quiet
	Adx           float64                `protobuf:"fixed64,2,opt,name=adx,proto3" json:"adx,omitempty"`
	AtrPercent    float64                `protobuf:"fixed64,3,opt,name=atr_percent,json=atrPercent,proto3" json:"atr_percent,omitempty"`
	PlusDi        float64                `protobuf:"fixed64,4,opt,name=plus_di,json=plusDi,proto3" json:"plus_di,omitempty"`
	MinusDi       float64                `protobuf:"fixed64,5,opt,name=minus_di,json=minusDi,proto3" json:"minus_di,omitempty"`
	TrendDir      string                 `protobuf:"bytes,6,opt,name=trend_dir,json=trendDir,proto3" json:"trend_dir,omitempty"` // UP, DOWN, NEUTRAL
	Confidence    float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`           // 0-100
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegimeResponse) Reset() {
	*x = RegimeResponse{}
	mi := &file_indicators_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegimeResponse) ProtoMessage() {}

func (x *RegimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegimeResponse.ProtoReflect.Descriptor instead.
func (*RegimeResponse) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{18}
}

func (x *RegimeResponse) GetRegime() string {
	if x != nil {
		return x.Regime
	}
	return ""
}

func (x *RegimeResponse) GetAdx() float64 {
	if x != nil {
		return x.Adx
	}
	return 0
}

func (x *RegimeResponse) GetAtrPercent() float64 {
	if x != nil {
		return x.AtrPercent
	}
	return 0
}

func (x *RegimeResponse) GetPlusDi() float64 {
	if x != nil {
		return x.PlusDi
	}
	return 0
}

func (x *RegimeResponse) GetMinusDi() float64 {
	if x != nil {
		return x.MinusDi
	}
	return 0
}

func (x *RegimeResponse) GetTrendDir() string {
	if x != nil {
		return x.TrendDir
	}
	return ""
}

func (x *RegimeResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RegimeResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AnalyzeAllRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Candles         []*Candle              `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	RsiPeriod       int32                  `protobuf:"varint,2,opt,name=rsi_period,json=rsiPeriod,proto3" json:"rsi_period,omitempty"`
	MacdFast        int32                  `protobuf:"varint,3,opt,name=macd_fast,json=macdFast,proto3" json:"macd_fast,omitempty"`
	MacdSlow        int32                  `protobuf:"varint,4,opt,name=macd_slow,json=macdSlow,proto3" json:"macd_slow,omitempty"`
	MacdSignal      int32                  `protobuf:"varint,5,opt,name=macd_signal,json=macdSignal,proto3" json:"macd_signal,omitempty"`
	BbPeriod        int32                  `protobuf:"varint,6,opt,name=bb_period,json=bbPeriod,proto3" json:"bb_period,omitempty"`
	BbStdDev        float64                `protobuf:"fixed64,7,opt,name=bb_std_dev,json=bbStdDev,proto3" json:"bb_std_dev,omitempty"`
	EmaPeriod       int32                  `protobuf:"varint,8,opt,name=ema_period,json=emaPeriod,proto3" json:"ema_period,omitempty"`
	VolumeLookback  int32                  `protobuf:"varint,9,opt,name=volume_lookback,json=volumeLookback,proto3" json:"volume_lookback,omitempty"`
	VolumeThreshold float64                `protobuf:"fixed64,10,opt,name=volume_threshold,json=volumeThreshold,proto3" json:"volume_threshold,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeAllRequest) Reset() {
	*x = AnalyzeAllRequest{}
	mi := &file_indicators_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeAllRequest) ProtoMessage() {}

func (x *AnalyzeAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeAllRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeAllRequest) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{19}
}

func (x *AnalyzeAllRequest) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *AnalyzeAllRequest) GetRsiPeriod() int32 {
	if x != nil {
		return x.RsiPeriod
	}
	return 0
}

func (x *AnalyzeAllRequest) GetMacdFast() int32 {
	if x != nil {
		return x.MacdFast
	}
	return 0
}

func (x *AnalyzeAllRequest) GetMacdSlow() int32 {
	if x != nil {
		return x.MacdSlow
	}
	return 0
}

func (x *AnalyzeAllRequest) GetMacdSignal() int32 {
	if x != nil {
		return x.MacdSignal
	}
	return 0
}

func (x *AnalyzeAllRequest) GetBbPeriod() int32 {
	if x != nil {
		return x.BbPeriod
	}
	return 0
}

func (x *AnalyzeAllRequest) GetBbStdDev() float64 {
	if x != nil {
		return x.BbStdDev
	}
	return 0
}

func (x *AnalyzeAllRequest) GetEmaPeriod() int32 {
	if x != nil {
		return x.EmaPeriod
	}
	return 0
}

func (x *AnalyzeAllRequest) GetVolumeLookback() int32 {
	if x != nil {
		return x.VolumeLookback
	}
	return 0
}

func (x *AnalyzeAllRequest) GetVolumeThreshold() float64 {
	if x != nil {
		return x.VolumeThreshold
	}
	return 0
}

type AnalyzeAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rsi           *RSIResponse           `protobuf:"bytes,1,opt,name=rsi,proto3" json:"rsi,omitempty"`
	Macd          *MACDResponse          `protobuf:"bytes,2,opt,name=macd,proto3" json:"macd,omitempty"`
	Bollinger     *BollingerResponse     `protobuf:"bytes,3,opt,name=bollinger,proto3" json:"bollinger,omitempty"`
	Ema           *EMAResponse           `protobuf:"bytes,4,opt,name=ema,proto3" json:"ema,omitempty"`
	Volume        *VolumeResponse        `protobuf:"bytes,5,opt,name=volume,proto3" json:"volume,omitempty"`
	OverallSignal string                 `protobuf:"bytes,6,opt,name=overall_signal,json=overallSignal,proto3" json:"overall_signal,omitempty"` // STRONG_BUY, BUY, NEUTRAL, SELL, STRONG_SELL
	BullishCount  int32                  `protobuf:"varint,7,opt,name=bullish_count,json=bullishCount,proto3" json:"bullish_count,omitempty"`
	BearishCount  int32                  `protobuf:"varint,8,opt,name=bearish_count,json=bearishCount,proto3" json:"bearish_count,omitempty"`
	Atr           *ATRResponse           `protobuf:"bytes,9,opt,name=atr,proto3" json:"atr,omitempty"`
	Adx           *ADXResponse           `protobuf:"bytes,10,opt,name=adx,proto3" json:"adx,omitempty"`
	Stochastic    *StochasticResponse    `protobuf:"bytes,11,opt,name=stochastic,proto3" json:"stochastic,omitempty"`
	Regime        *RegimeResponse        `protobuf:"bytes,12,opt,name=regime,proto3" json:"regime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeAllResponse) Reset() {
	*x = AnalyzeAllResponse{}
	mi := &file_indicators_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeAllResponse) ProtoMessage() {}

func (x *AnalyzeAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indicators_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeAllResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeAllResponse) Descriptor() ([]byte, []int) {
	return file_indicators_proto_rawDescGZIP(), []int{20}
}

func (x *AnalyzeAllResponse) GetRsi() *RSIResponse {
	if x != nil {
		return x.Rsi
	}
	return nil
}

func (x *AnalyzeAllResponse) GetMacd() *MACDResponse {
	if x != nil {
		return x.Macd
	}
	return nil
}

func (x *AnalyzeAllResponse) GetBollinger() *BollingerResponse {
	if x != nil {
		return x.Bollinger
	}
	return nil
}

func (x *AnalyzeAllResponse) GetEma() *EMAResponse {
	if x != nil {
		return x.Ema
	}
	return nil
}

func (x *AnalyzeAllResponse) GetVolume() *VolumeResponse {
	if x != nil {
		return x.Volume
	}
	return nil
}

func (x *AnalyzeAllResponse) GetOverallSignal() string {
	if x != nil {
		return x.OverallSignal
	}
	return ""
}

func (x *AnalyzeAllResponse) GetBullishCount() int32 {
	if x != nil {
		return x.BullishCount
	}
	return 0
}

func (x *AnalyzeAllResponse) GetBearishCount() int32 {
	if x != nil {
		return x.BearishCount
	}
	return 0
}

func (x *AnalyzeAllResponse) GetAtr() *ATRResponse {
	if x != nil {
		return x.Atr
	}
	return nil
}

func (x *AnalyzeAllResponse) GetAdx() *ADXResponse {
	if x != nil {
		return x.Adx
	}
	return nil
}

func (x *AnalyzeAllResponse) GetStochastic() *StochasticResponse {
	if x != nil {
		return x.Stochastic
	}
	return nil
}

func (x *AnalyzeAllResponse) GetRegime() *RegimeResponse {
	if x != nil {
		return x.Regime
	}
	return nil
}

var File_indicators_proto protoreflect.FileDescriptor

const file_indicators_proto_rawDesc = "" +
	"\n" +
	"\x10indicators.proto\x12\n" +
	"indicators\"\x8e\x01\n" +
	"\x06Candle\x12\x12\n" +
	"\x04open\x18\x01 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x03 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x04 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x01R\x06volume\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"R\n" +
	"\n" +
	"RSIRequest\x12,\n" +
	"\acandles\x18\x01 \x03(\v2\x12.indicators.CandleR\acandles\x12\x16\n" +
	"\x06period\x18\x02 \x01(\x05R\x06period\"S\n" +
	"\vRSIResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\x12\x16\n" +
	"\x06series\x18\x03 \x03(\x01R\x06series\"\xa2\x01\n" +
	"\vMACDRequest\x12,\n" +
	"\acandles\x18\x01 \x03(\v2\x12.indicators.CandleR\acandles\x12\x1f\n" +
	"\vfast_period\x18\x02 \x01(\x05R\n" +
	"fastPeriod\x12\x1f\n" +
	"\vslow_period\x18\x03 \x01(\x05R\n" +
	"slowPeriod\x12#\n" +
	"\rsignal_period\x18\x04 \x01(\x05R\fsignalPeriod\"\x91\x02\n" +
	"\fMACDResponse\x12\x1b\n" +
	"\tmacd_line\x18\x01 \x01(\x01R\bmacdLine\x12\x1f\n" +
	"\vsignal_line\x18\x02 \x01(\x01R\n" +
	"signalLine\x12\x1c\n" +
	"\thistogram\x18\x03 \x01(\x01R\thistogram\x12\x16\n" +
	"\x06signal\x18\x04 \x01(\tR\x06signal\x12\x1c\n" +
	"\tcrossover\x18\x05 \x01(\bR\tcrossover\x12\x1f\n" +
	"\vmacd_series\x18\x06 \x03(\x01R\n" +
	"macdSeries\x12#\n" +
	"\rsignal_series\x18\a \x03(\x01R\fsignalSeries\x12)\n" +
	"\x10histogram_series\x18\b \x03(\x01R\x0fhistogramSeries\"q\n" +
	"\x10BollingerRequest\x12,\n" +
	"\acandles\x18\x01 \x03(\v2\x12.indicators.CandleR\acandles\x12\x16\n" +
	"\x06period\x18\x02 \x01(\x05R\x06period\x12\x17\n" +
	"\astd_dev\x18\x03 \x01(\x01R\x06stdDev\"\x95\x02\n" +
	"\x11BollingerResponse\x12\x14\n" +
	"\x05upper\x18\x01 \x01(\x01R\x05upper\x12\x16\n" +
	"\x06middle\x18\x02 \x01(\x01R\x06middle\x12\x14\n" +
	"\x05lower\x18\x03 \x01(\x01R\x05lower\x12\x1c\n" +
	"\tbandwidth\x18\x04 \x01(\x01R\tbandwidth\x12\x1b\n" +
	"\tpercent_b\x18\x05 \x01(\x01R\bpercentB\x12\x16\n" +
	"\x06signal\x18\x06 \x01(\tR\x06signal\x12!\n" +
	"\fupper_series\x18\a \x03(\x01R\vupperSeries\x12#\n" +
	"\rmiddle_series\x18\b \x03(\x01R\fmiddleSeries\x12!\n" +
	"\flower_series\x18\t \x03(\x01R\vlowerSeries\"R\n" +
	"\n" +
	"EMARequest\x12,\n" +
	"\acandles\x18\x01 \x03(\v2\x12.indicators.CandleR\acandles\x12\x16\n" +
	"\x06period\x18\x02 \x01(\x05R\x06period\"Q\n" +
	"\vEMAResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x14\n" +
	"\x05trend\x18\x02 \x01(\tR\x05trend\x12\x16\n" +
	"\x06series\x18\x03 \x03(\x01R\x06series\"w\n" +
	"\rVolumeRequest\x12,\n" +
	"\acandles\x18\x01 \x03(\v2\x12.indicators.CandleR\acandles\x12\x1a\n" +
	"\blookback\x18\x02 \x01(\x05R\blookback\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x01R\tthreshold\"\xa7\x01\n" +
	"\x0eVolumeResponse\x12\x19\n" +
	"\bis_spike\x18\x01 \x01(\bR\aisSpike\x12%\n" +
	"\x0ecurrent_volume\x18\x02 \x01(\x01R\rcurrentVolume\x12%\n" +
	"\x0eaverage_volume\x18\x03 \x01(\x01R\raverageVolume\x12\x14\n" +
	"\x05ratio\x18\x04 \x01(\x01R\x05ratio\x12\x16\n" +
	"\x06signal\x18\x05 \x01(\tR\x06signal\"R\n" +
	"\n" +
	"ATRRequest\x12,\n" +
	"\acandles\x18\x01 \x03(\v2\x12.indicators.CandleR\acandles\x12\x16\n" +
	"\x06period\x18\x02 \x01(\x05R\x06period\"m\n" +
	"\vATRResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x01R\apercent\x12\x16\n" +
	"\x06signal\x18\x03 \x01(\tR\x06signal\x12\x16\n" +
	"\x06series\x18\x04 \x03(\x01R\x06series\"R\n" +
	"\n" +
	"ADXRequest\x12,\n" +
	"\acandles\x18\x01 \x03(\v2\x12.indicators.CandleR\acandles\x12\x16\n" +
	"\x06period\x18\x02 \x01(\x05R\x06period\"\xa4\x01\n" +
	"\vADXResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x17\n" +
	"\aplus_di\x18\x02 \x01(\x01R\x06plusDi\x12\x19\n" +
	"\bminus_di\x18\x03 \x01(\x01R\aminusDi\x12\x16\n" +
	"\x06signal\x18\x04 \x01(\tR\x06signal\x12\x1b\n" +
	"\ttrend_dir\x18\x05 \x01(\tR\btrendDir\x12\x16\n" +
	"\x06series\x18\x06 \x03(\x01R\x06series\"\x8f\x01\n" +
	"\x11StochasticRequest\x12,\n" +
	"\acandles\x18\x01 \x03(\v2\x12.indicators.CandleR\acandles\x12\x19\n" +
	"\bk_period\x18\x02 \x01(\x05R\akPeriod\x12\x19\n" +
	"\bd_period\x18\x03 \x01(\x05R\adPeriod\x12\x16\n" +
	"\x06smooth\x18\x04 \x01(\x05R\x06smooth\"~\n" +
	"\x12StochasticResponse\x12\f\n" +
	"\x01k\x18\x01 \x01(\x01R\x01k\x12\f\n" +
	"\x01d\x18\x02 \x01(\x01R\x01d\x12\x16\n" +
	"\x06signal\x18\x03 \x01(\tR\x06signal\x12\x19\n" +
	"\bk_series\x18\x04 \x03(\x01R\akSeries\x12\x19\n" +
	"\bd_series\x18\x05 \x03(\x01R\adSeries\"U\n" +
	"\rRegimeRequest\x12,\n" +
	"\acandles\x18\x01 \x03(\v2\x12.indicators.CandleR\acandles\x12\x16\n" +
	"\x06period\x18\x02 \x01(\x05R\x06period\"\xee\x01\n" +
	"\x0eRegimeResponse\x12\x16\n" +
	"\x06regime\x18\x01 \x01(\tR\x06regime\x12\x10\n" +
	"\x03adx\x18\x02 \x01(\x01R\x03adx\x12\x1f\n" +
	"\vatr_percent\x18\x03 \x01(\x01R\n" +
	"atrPercent\x12\x17\n" +
	"\aplus_di\x18\x04 \x01(\x01R\x06plusDi\x12\x19\n" +
	"\bminus_di\x18\x05 \x01(\x01R\aminusDi\x12\x1b\n" +
	"\ttrend_dir\x18\x06 \x01(\tR\btrendDir\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\"\xe9\x02\n" +
	"\x11AnalyzeAllRequest\x12,\n" +
	"\acandles\x18\x01 \x03(\v2\x12.indicators.CandleR\acandles\x12\x1d\n" +
	"\n" +
	"rsi_period\x18\x02 \x01(\x05R\trsiPeriod\x12\x1b\n" +
	"\tmacd_fast\x18\x03 \x01(\x05R\bmacdFast\x12\x1b\n" +
	"\tmacd_slow\x18\x04 \x01(\x05R\bmacdSlow\x12\x1f\n" +
	"\vmacd_signal\x18\x05 \x01(\x05R\n" +
	"macdSignal\x12\x1b\n" +
	"\tbb_period\x18\x06 \x01(\x05R\bbbPeriod\x12\x1c\n" +
	"\n" +
	"bb_std_dev\x18\a \x01(\x01R\bbbStdDev\x12\x1d\n" +
	"\n" +
	"ema_period\x18\b \x01(\x05R\temaPeriod\x12'\n" +
	"\x0fvolume_lookback\x18\t \x01(\x05R\x0evolumeLookback\x12)\n" +
	"\x10volume_threshold\x18\n" +
	" \x01(\x01R\x0fvolumeThreshold\"\xc4\x04\n" +
	"\x12AnalyzeAllResponse\x12)\n" +
	"\x03rsi\x18\x01 \x01(\v2\x17.indicators.RSIResponseR\x03rsi\x12,\n" +
	"\x04macd\x18\x02 \x01(\v2\x18.indicators.MACDResponseR\x04macd\x12;\n" +
	"\tbollinger\x18\x03 \x01(\v2\x1d.indicators.BollingerResponseR\tbollinger\x12)\n" +
	"\x03ema\x18\x04 \x01(\v2\x17.indicators.EMAResponseR\x03ema\x122\n" +
	"\x06volume\x18\x05 \x01(\v2\x1a.indicators.VolumeResponseR\x06volume\x12%\n" +
	"\x0eoverall_signal\x18\x06 \x01(\tR\roverallSignal\x12#\n" +
	"\rbullish_count\x18\a \x01(\x05R\fbullishCount\x12#\n" +
	"\rbearish_count\x18\b \x01(\x05R\fbearishCount\x12)\n" +
	"\x03atr\x18\t \x01(\v2\x17.indicators.ATRResponseR\x03atr\x12)\n" +
	"\x03adx\x18\n" +
	" \x01(\v2\x17.indicators.ADXResponseR\x03adx\x12>\n" +
	"\n" +
	"stochastic\x18\v \x01(\v2\x1e.indicators.StochasticResponseR\n" +
	"stochastic\x122\n" +
	"\x06regime\x18\f \x01(\v2\x1a.indicators.RegimeResponseR\x06regime2\xed\x05\n" +
	"\x13TechnicalIndicators\x12?\n" +
	"\fCalculateRSI\x12\x16.indicators.RSIRequest\x1a\x17.indicators.RSIResponse\x12B\n" +
	"\rCalculateMACD\x12\x17.indicators.MACDRequest\x1a\x18.indicators.MACDResponse\x12V\n" +
	"\x17CalculateBollingerBands\x12\x1c.indicators.BollingerRequest\x1a\x1d.indicators.BollingerResponse\x12?\n" +
	"\fCalculateEMA\x12\x16.indicators.EMARequest\x1a\x17.indicators.EMAResponse\x12J\n" +
	"\x11DetectVolumeSpike\x12\x19.indicators.VolumeRequest\x1a\x1a.indicators.VolumeResponse\x12?\n" +
	"\fCalculateATR\x12\x16.indicators.ATRRequest\x1a\x17.indicators.ATRResponse\x12?\n" +
	"\fCalculateADX\x12\x16.indicators.ADXRequest\x1a\x17.indicators.ADXResponse\x12T\n" +
	"\x13CalculateStochastic\x12\x1d.indicators.StochasticRequest\x1a\x1e.indicators.StochasticResponse\x12G\n" +
	"\x0eClassifyRegime\x12\x19.indicators.RegimeRequest\x1a\x1a.indicators.RegimeResponse\x12K\n" +
	"\n" +
	"AnalyzeAll\x12\x1d.indicators.AnalyzeAllRequest\x1a\x1e.indicators.AnalyzeAllResponseB7Z5github.com/trading-bot/go-bot/internal/analysis/protob\x06proto3"

var (
	file_indicators_proto_rawDescOnce sync.Once
	file_indicators_proto_rawDescData []byte
)

func file_indicators_proto_rawDescGZIP() []byte {
	file_indicators_proto_rawDescOnce.Do(func() {
		file_indicators_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indicators_proto_rawDesc), len(file_indicators_proto_rawDesc)))
	})
	return file_indicators_proto_rawDescData
}

var file_indicators_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_indicators_proto_goTypes = []any{
	(*Candle)(nil),             // 0: indicators.Candle
	(*RSIRequest)(nil),         // 1: indicators.RSIRequest
	(*RSIResponse)(nil),        // 2: indicators.RSIResponse
	(*MACDRequest)(nil),        // 3: indicators.MACDRequest
	(*MACDResponse)(nil),       // 4: indicators.MACDResponse
	(*BollingerRequest)(nil),   // 5: indicators.BollingerRequest
	(*BollingerResponse)(nil),  // 6: indicators.BollingerResponse
	(*EMARequest)(nil),         // 7: indicators.EMARequest
	(*EMAResponse)(nil),        // 8: indicators.EMAResponse
	(*VolumeRequest)(nil),      // 9: indicators.VolumeRequest
	(*VolumeResponse)(nil),     // 10: indicators.VolumeResponse
	(*ATRRequest)(nil),         // 11: indicators.ATRRequest
	(*ATRResponse)(nil),        // 12: indicators.ATRResponse
	(*ADXRequest)(nil),         // 13: indicators.ADXRequest
	(*ADXResponse)(nil),        // 14: indicators.ADXResponse
	(*StochasticRequest)(nil),  // 15: indicators.StochasticRequest
	(*StochasticResponse)(nil), // 16: indicators.StochasticResponse
	(*RegimeRequest)(nil),      // 17: indicators.RegimeRequest
	(*RegimeResponse)(nil),     // 18: indicators.RegimeResponse
	(*AnalyzeAllRequest)(nil),  // 19: indicators.AnalyzeAllRequest
	(*AnalyzeAllResponse)(nil), // 20: indicators.AnalyzeAllResponse
}
var file_indicators_proto_depIdxs = []int32{
	0,  // 0: indicators.RSIRequest.candles:type_name -> indicators.Candle
	0,  // 1: indicators.MACDRequest.candles:type_name -> indicators.Candle
	0,  // 2: indicators.BollingerRequest.candles:type_name -> indicators.Candle
	0,  // 3: indicators.EMARequest.candles:type_name -> indicators.Candle
	0,  // 4: indicators.VolumeRequest.candles:type_name -> indicators.Candle
	0,  // 5: indicators.ATRRequest.candles:type_name -> indicators.Candle
	0,  // 6: indicators.ADXRequest.candles:type_name -> indicators.Candle
	0,  // 7: indicators.StochasticRequest.candles:type_name -> indicators.Candle
	0,  // 8: indicators.RegimeRequest.candles:type_name -> indicators.Candle
	0,  // 9: indicators.AnalyzeAllRequest.candles:type_name -> indicators.Candle
	2,  // 10: indicators.AnalyzeAllResponse.rsi:type_name -> indicators.RSIResponse
	4,  // 11: indicators.AnalyzeAllResponse.macd:type_name -> indicators.MACDResponse
	6,  // 12: indicators.AnalyzeAllResponse.bollinger:type_name -> indicators.BollingerResponse
	8,  // 13: indicators.AnalyzeAllResponse.ema:type_name -> indicators.EMAResponse
	10, // 14: indicators.AnalyzeAllResponse.volume:type_name -> indicators.VolumeResponse
	12, // 15: indicators.AnalyzeAllResponse.atr:type_name -> indicators.ATRResponse
	14, // 16: indicators.AnalyzeAllResponse.adx:type_name -> indicators.ADXResponse
	16, // 17: indicators.AnalyzeAllResponse.stochastic:type_name -> indicators.StochasticResponse
	18, // 18: indicators.AnalyzeAllResponse.regime:type_name -> indicators.RegimeResponse
	1,  // 19: indicators.TechnicalIndicators.CalculateRSI:input_type -> indicators.RSIRequest
	3,  // 20: indicators.TechnicalIndicators.CalculateMACD:input_type -> indicators.MACDRequest
	5,  // 21: indicators.TechnicalIndicators.CalculateBollingerBands:input_type -> indicators.BollingerRequest
	7,  // 22: indicators.TechnicalIndicators.CalculateEMA:input_type -> indicators.EMARequest
	9,  // 23: indicators.TechnicalIndicators.DetectVolumeSpike:input_type -> indicators.VolumeRequest
	11, // 24: indicators.TechnicalIndicators.CalculateATR:input_type -> indicators.ATRRequest
	13, // 25: indicators.TechnicalIndicators.CalculateADX:input_type -> indicators.ADXRequest
	15, // 26: indicators.TechnicalIndicators.CalculateStochastic:input_type -> indicators.StochasticRequest
	17, // 27: indicators.TechnicalIndicators.ClassifyRegime:input_type -> indicators.RegimeRequest
	19, // 28: indicators.TechnicalIndicators.AnalyzeAll:input_type -> indicators.AnalyzeAllRequest
	2,  // 29: indicators.TechnicalIndicators.CalculateRSI:output_type -> indicators.RSIResponse
	4,  // 30: indicators.TechnicalIndicators.CalculateMACD:output_type -> indicators.MACDResponse
	6,  // 31: indicators.TechnicalIndicators.CalculateBollingerBands:output_type -> indicators.BollingerResponse
	8,  // 32: indicators.TechnicalIndicators.CalculateEMA:output_type -> indicators.EMAResponse
	10, // 33: indicators.TechnicalIndicators.DetectVolumeSpike:output_type -> indicators.VolumeResponse
	12, // 34: indicators.TechnicalIndicators.CalculateATR:output_type -> indicators.ATRResponse
	14, // 35: indicators.TechnicalIndicators.CalculateADX:output_type -> indicators.ADXResponse
	16, // 36: indicators.TechnicalIndicators.CalculateStochastic:output_type -> indicators.StochasticResponse
	18, // 37: indicators.TechnicalIndicators.ClassifyRegime:output_type -> indicators.RegimeResponse
	20, // 38: indicators.TechnicalIndicators.AnalyzeAll:output_type -> indicators.AnalyzeAllResponse
	29, // [29:39] is the sub-list for method output_type
	19, // [19:29] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_indicators_proto_init() }
func file_indicators_proto_init() {
	if File_indicators_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indicators_proto_rawDesc), len(file_indicators_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_indicators_proto_goTypes,
		DependencyIndexes: file_indicators_proto_depIdxs,
		MessageInfos:      file_indicators_proto_msgTypes,
	}.Build()
	File_indicators_proto = out.File
	file_indicators_proto_goTypes = nil
	file_indicators_proto_depIdxs = nil
}
